#!/usr/bin/env bash

# -------------------------------
# IMPORTANT:
# This script is a module and should be sourced by other scripts!
# -------------------------------
# AUTHOR .... marcus.trommen@gmx.net
# CREATED ... 20210522
# -------------------------------

# -------------------------------
# FUNCTIION write_config ()
# write current variables to a config file for further use by other scripts
# INPUT
#     none
# RETURN:
#     none
# -------------------------------
function write_config {
	CONFIG_FILE="${SCAN_SCRIPT_BASE_DIRECTORY}/config"

	CONFIG_CONTENT=$(cat <<-EOF
#!/usr/bin/env bash

# IMPORTANT:
# This file is generated by config_handler.sh. 
# Do not make manual changes!
# 
# These symbols are intentionally not exported
# for not being visible in any subprocesses
# unless beeing sourced

DIALOG=/usr/bin/dialog

BUTTON_OK=0
BUTTON_YES=0
BUTTON_NO=1
BUTTON_CANCEL=1
KEY_CTRL_1=1
BUTTON_HELP=2
BUTTON_EXTRA=3
KEY_ESC=255

SCAN_SCRIPT_BASE_DIRECTORY="${SCAN_SCRIPT_BASE_DIRECTORY}"
SCAN_DEVICE="${SCAN_DEVICE}"
SCAN_PDF_FONT="${SCAN_PDF_FONT}"
SCAN_ARCHIVE_BASE_DIRECTORY="${SCAN_ARCHIVE_BASE_DIRECTORY}"
SCAN_WORKING_DIRECTORY="${SCAN_WORKING_DIRECTORY}"
SCAN_PAGE_START_NUMBER=${SCAN_PAGE_START_NUMBER}
SCAN_DOCUMENT_ID="${SCAN_DOCUMENT_ID}"
SCAN_DOCUMENT_TITLE="${SCAN_DOCUMENT_TITLE}"
SCAN_DOCUMENT_KEYWORDS="${SCAN_DOCUMENT_KEYWORDS}"
SCAN_DOCUMENT_FILE="${SCAN_DOCUMENT_FILE}"
SCAN_DOCUMENT_STORAGE_LOCATION="${SCAN_DOCUMENT_STORAGE_LOCATION}"
EOF
)
	echo "${CONFIG_CONTENT}" > ${CONFIG_FILE}
}


# -------------------------------
# FUNCTIION reset_metadata ()
# resets some variables of the config file to 
#     *   empty strings (if string variables)
#     *   zero (if numeric variables)
#     *   default values (if variables should have values)
#
# Be aware of configuration is not written to file by this function!
#
# INPUT
#     none
# RETURN:
#     none
# -------------------------------
function reset_metadata {
	SCAN_SCRIPT_BASE_DIRECTORY="$(dirname $(realpath $0))"

	# --------------------------------------------
	# SET Archive Base Directory
	# --------------------------------------------
	# alternative 1: directory of this script
	SCAN_ARCHIVE_BASE_DIRECTORY="${SCAN_SCRIPT_BASE_DIRECTORY}"

	# alternative 2: external USB HDD
	#SCAN_ARCHIVE_BASE_DIRECTORY="/media/marco/marco/DocArchive"

	# alternative 3: 16 GB USB Stick intenso
	#SCAN_ARCHIVE_BASE_DIRECTORY="/media/marco/DOC_ARCHIVE/docarchive"
	
	# you need to define full qualified path to font file!
	SCAN_PDF_FONT="/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
	SCAN_DEVICE=""

	SCAN_PAGE_START_NUMBER=1
	SCAN_DOCUMENT_ID=""
	SCAN_DOCUMENT_TITLE=""
	SCAN_DOCUMENT_KEYWORDS=""
	SCAN_DOCUMENT_FILE=""
	SCAN_DOCUMENT_STORAGE_LOCATION=""
}